### ISSUE TITLE
0.3.0 release

### ISSUE THREAD

**Issue by brody2consult** [bangkokjs/prettierx-0.4.x-fork#27]
* [x] ~~Drop Node.js 4 (#25)~~
* Include features from the following PRs:
  - [x] `--align-object-properties` option - PR #35
  - [x] `--no-indent-chains` option - PR #5

Should come after the following:
* [x] ~~resolve Azure Pipelines CI failures (#21)~~
* [x] ~~`0.0.2` release with changes from upstream prettier (#24)~~
